on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build docker image
      run: docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t twilio-microvisor-hal-stm32u5 .
    - name: Build code
      run: docker run --rm -v $(pwd)/:/home/ --name twilio-microvisor-hal-stm32u5 twilio-microvisor-hal-stm32u5
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: twilio-microvisor-hal-stm32u5
        path: |
          ${{ github.workspace }}/build/libtwilio-microvisor-hal-stm32u5.*
          ${{ github.workspace }}/mv_bitops.h
          ${{ github.workspace }}/Drivers/STM32U5xx_HAL_Driver/Inc
          ${{ github.workspace }}/Drivers/CMSIS/Device/ST/STM32U5xx/Include
          ${{ github.workspace }}/Drivers/CMSIS/Include
